"""
tests/test_recommendations.py
------------------------------
Unit tests for GET /recommendations/{meal_id}.

All Supabase, OpenAI, and knowledge_service calls are mocked — no live
credentials or network access required.

Run with:
    python -m pytest tests/test_recommendations.py -v
"""

import sys
import types
import unittest
from unittest.mock import AsyncMock, MagicMock, patch

# ---------------------------------------------------------------------------
# Bootstrap: stub ALL heavy optional dependencies BEFORE any app module loads.
# The stubs must be in sys.modules before the FastAPI app and routers import
# so that module-level initialisation (init_supabase, ChromaDB, OpenAI) never
# runs real code or reads environment variables.
# ---------------------------------------------------------------------------

# Stub `supabase` SDK
_supabase_mod = types.ModuleType("supabase")
_supabase_mod.create_client = MagicMock(return_value=MagicMock())
sys.modules.setdefault("supabase", _supabase_mod)

# Stub `chromadb` (knowledge_service imports this)
_chromadb_stub = types.ModuleType("chromadb")
_chromadb_stub.PersistentClient = MagicMock()
sys.modules.setdefault("chromadb", _chromadb_stub)

# Stub `openai` (knowledge_service imports this)
_openai_stub = types.ModuleType("openai")
_openai_stub.OpenAI = MagicMock()
sys.modules.setdefault("openai", _openai_stub)

# Stub `db.supabase_client` so the real init_supabase() is never called.
# The `supabase` attribute starts as None; each test replaces it via patch().
# This is the same pattern used by test_knowledge_service.py for chromadb.
_db_pkg_stub = types.ModuleType("db")
sys.modules.setdefault("db", _db_pkg_stub)

_db_supabase_stub = types.ModuleType("db.supabase_client")
_db_supabase_stub.supabase = None          # overridden per-test via patch()
sys.modules["db.supabase_client"] = _db_supabase_stub  # always replace, not setdefault

# ---------------------------------------------------------------------------
# Now it's safe to import the FastAPI app and TestClient
# ---------------------------------------------------------------------------
from fastapi.testclient import TestClient
from main import app  # noqa: E402 — must come after sys.modules stubs

client = TestClient(app)

# ---------------------------------------------------------------------------
# Shared constants (mirrored from the router for assertion comparisons)
# ---------------------------------------------------------------------------

ADA_FALLBACK_MESSAGE = (
    "Based on American Diabetes Association guidelines, "
    "balancing your plate with lean protein, non-starchy "
    "vegetables, and complex carbs is recommended. "
    "[Source: ADA Standards of Care]"
)
DISCLAIMER = (
    "⚠️ Generated by AI based on recent literature. "
    "This is not medical advice. Always consult your doctor."
)

# A valid UUID v4 to use across all positive-path tests
VALID_MEAL_ID = "12345678-1234-4abc-89ab-123456789abc"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_meal_row(meal_id: str = VALID_MEAL_ID, user_id: str = "user-uuid-001") -> dict:
    """Minimal Supabase meals row."""
    return {
        "id": meal_id,
        "user_id": user_id,
        "photo_url": None,
        "identified_foods": [
            {"food_name": "brown rice",     "confidence_score": 0.95},
            {"food_name": "grilled salmon", "confidence_score": 0.97},
        ],
        "timestamp": "2026-03-07T20:00:00+00:00",
    }


def _make_glucose_row(value: int = 145) -> list[dict]:
    return [{"value": value}]


def _make_research(
    journal: str = "Diabetes Care",
    year: int = 2022,
    pubmed_id: str = "36101234",
    similarity: float = 0.88,
) -> dict:
    return {
        "abstract_text": (
            "A low-glycemic diet rich in omega-3 fatty acids significantly "
            "reduced postprandial glucose in patients with type 2 diabetes."
        ),
        "journal": journal,
        "year":    year,
        "pubmed_id": pubmed_id,
        "similarity": similarity,
    }


def _mock_supabase_chain(meal_data: dict | None, glucose_data: list) -> MagicMock:
    """
    Builds a MagicMock Supabase client whose .table() route returns the right
    fake data for meals, glucose_readings, and recommendations tables.
    """
    sb = MagicMock()

    # --- meals table chain --------------------------------------------------
    meals_execute  = MagicMock()
    meals_execute.data = [meal_data] if meal_data else []
    meals_chain    = MagicMock()
    meals_chain.execute.return_value = meals_execute
    meals_chain.limit.return_value   = meals_chain
    meals_chain.eq.return_value      = meals_chain
    meals_chain.select.return_value  = meals_chain

    # --- glucose_readings table chain ---------------------------------------
    gluc_execute  = MagicMock()
    gluc_execute.data = glucose_data
    gluc_chain    = MagicMock()
    gluc_chain.execute.return_value = gluc_execute
    gluc_chain.limit.return_value   = gluc_chain
    gluc_chain.order.return_value   = gluc_chain
    gluc_chain.eq.return_value      = gluc_chain
    gluc_chain.select.return_value  = gluc_chain

    # --- recommendations table chain ----------------------------------------
    rec_execute   = MagicMock()
    rec_execute.data = [{"id": "rec-uuid-001"}]
    rec_chain     = MagicMock()
    rec_chain.execute.return_value = rec_execute
    rec_chain.insert.return_value  = rec_chain

    def _table_router(name: str) -> MagicMock:
        return {"meals": meals_chain, "glucose_readings": gluc_chain,
                "recommendations": rec_chain}.get(name, MagicMock())

    sb.table.side_effect = _table_router
    return sb


# ---------------------------------------------------------------------------
# Test cases
# ---------------------------------------------------------------------------

class TestGetRecommendations(unittest.TestCase):

    # ── Happy path: research found & GPT cites journal + year ────────────

    @patch("routers.recommendations._call_gpt4o", new_callable=AsyncMock)
    @patch("routers.recommendations.knowledge_service.query_research")
    @patch("routers.recommendations._save_recommendation", new_callable=AsyncMock)
    def test_successful_gpt_with_citation(self, mock_save, mock_research, mock_gpt):
        """
        Scenario: glucose=145, brown rice + grilled salmon.
        Research similarity 0.88, GPT cites 'Diabetes Care' and '2022'.
        Expect: 200, source='gpt4o', tip contains citation, disclaimer present.
        """
        mock_research.return_value = _make_research(journal="Diabetes Care", year=2022)
        mock_gpt.return_value = (
            "Great news! A 2022 study in Diabetes Care found that pairing "
            "brown rice with omega-3-rich salmon slows glucose absorption. "
            "Try adding some leafy greens to make it even more balanced!"
        )
        mock_save.return_value = {"id": "rec-uuid-001"}

        with patch("db.supabase_client.supabase",
                   _mock_supabase_chain(_make_meal_row(), _make_glucose_row(145))):
            response = client.get(f"/recommendations/{VALID_MEAL_ID}")

        self.assertEqual(response.status_code, 200)
        body = response.json()
        self.assertEqual(body["status"], "success")
        self.assertEqual(body["source"], "gpt4o")
        self.assertIn("Diabetes Care", body["recommendation"])
        self.assertIn("2022", body["recommendation"])
        self.assertIn(DISCLAIMER, body["recommendation"])
        self.assertEqual(body["glucose_used_mg_dl"], 145)
        self.assertIsNotNone(body["research"])
        self.assertEqual(body["research"]["pubmed_id"], "36101234")

    # ── GPT omits citation on first attempt, includes on retry ───────────

    @patch("routers.recommendations._call_gpt4o", new_callable=AsyncMock)
    @patch("routers.recommendations.knowledge_service.query_research")
    @patch("routers.recommendations._save_recommendation", new_callable=AsyncMock)
    def test_retry_succeeds_on_second_attempt(self, mock_save, mock_research, mock_gpt):
        """
        Scenario: glucose=180, rice + salmon. First GPT omits citation → retry → pass.
        Expect: 200, source='gpt4o', GPT called exactly twice.
        """
        mock_research.return_value = _make_research(journal="Nutrients", year=2021)
        mock_gpt.side_effect = [
            # First attempt — no journal/year
            "Try eating more vegetables with every meal. They help regulate blood sugar.",
            # Second attempt — citation present
            ("According to a 2021 Nutrients study, adding non-starchy vegetables "
             "significantly lowers postprandial glucose. Enjoy your salmon and rice!"),
        ]
        mock_save.return_value = None

        with patch("db.supabase_client.supabase",
                   _mock_supabase_chain(_make_meal_row(), _make_glucose_row(180))):
            response = client.get(f"/recommendations/{VALID_MEAL_ID}")

        self.assertEqual(response.status_code, 200)
        body = response.json()
        self.assertEqual(body["source"], "gpt4o")
        self.assertIn("Nutrients", body["recommendation"])
        self.assertIn("2021", body["recommendation"])
        self.assertIn(DISCLAIMER, body["recommendation"])
        self.assertEqual(mock_gpt.call_count, 2)

    # ── Both GPT attempts omit citation → ADA fallback ───────────────────

    @patch("routers.recommendations._call_gpt4o", new_callable=AsyncMock)
    @patch("routers.recommendations.knowledge_service.query_research")
    @patch("routers.recommendations._save_recommendation", new_callable=AsyncMock)
    def test_both_attempts_fail_serves_ada_fallback(self, mock_save, mock_research, mock_gpt):
        """
        Scenario: glucose=95, rice + salmon. Both GPT attempts lack citation.
        Expect: ADA message served verbatim, source='ada_fallback', research=None.
        """
        mock_research.return_value = _make_research(journal="JAMA", year=2023)
        mock_gpt.return_value = "Try to eat more fiber-rich foods with every meal."
        mock_save.return_value = None

        with patch("db.supabase_client.supabase",
                   _mock_supabase_chain(_make_meal_row(), _make_glucose_row(95))):
            response = client.get(f"/recommendations/{VALID_MEAL_ID}")

        self.assertEqual(response.status_code, 200)
        body = response.json()
        self.assertEqual(body["source"], "ada_fallback")
        self.assertIn(ADA_FALLBACK_MESSAGE, body["recommendation"])
        self.assertIn(DISCLAIMER, body["recommendation"])
        self.assertIsNone(body["research"])
        self.assertEqual(mock_gpt.call_count, 2)   # Must have tried twice

    # ── knowledge_service returns FALLBACK_TO_ADA → GPT never called ─────

    @patch("routers.recommendations._call_gpt4o", new_callable=AsyncMock)
    @patch("routers.recommendations.knowledge_service.query_research")
    @patch("routers.recommendations._save_recommendation", new_callable=AsyncMock)
    def test_fallback_when_no_research_found(self, mock_save, mock_research, mock_gpt):
        """
        Scenario: glucose=110, ChromaDB finds no relevant abstract.
        Expect: ADA fallback, GPT never called.
        """
        mock_research.return_value = {"status": "FALLBACK_TO_ADA"}
        mock_save.return_value = None

        with patch("db.supabase_client.supabase",
                   _mock_supabase_chain(_make_meal_row(), _make_glucose_row(110))):
            response = client.get(f"/recommendations/{VALID_MEAL_ID}")

        self.assertEqual(response.status_code, 200)
        body = response.json()
        self.assertEqual(body["source"], "ada_fallback")
        self.assertIn(ADA_FALLBACK_MESSAGE, body["recommendation"])
        self.assertIn(DISCLAIMER, body["recommendation"])
        self.assertIsNone(body["research"])
        mock_gpt.assert_not_called()   # NEVER speculate beyond research

    # ── Meal not found in Supabase → 404 ─────────────────────────────────

    def test_meal_not_found_returns_404(self):
        """
        Scenario: Supabase has no row for this meal_id.
        Expect: 404 with meaningful detail.
        """
        with patch("db.supabase_client.supabase",
                   _mock_supabase_chain(meal_data=None, glucose_data=[])):
            response = client.get(f"/recommendations/{VALID_MEAL_ID}")

        self.assertEqual(response.status_code, 404)
        self.assertIn("not found", response.json()["detail"].lower())

    # ── Invalid UUID → 400 (no DB or ML calls) ───────────────────────────

    def test_invalid_uuid_returns_400(self):
        """Non-UUID meal_id is rejected before touching any external service."""
        response = client.get("/recommendations/not-a-valid-uuid")
        self.assertEqual(response.status_code, 400)
        self.assertIn("valid UUID", response.json()["detail"])

    # ── Disclaimer present on EVERY response path ─────────────────────────

    @patch("routers.recommendations._call_gpt4o", new_callable=AsyncMock)
    @patch("routers.recommendations.knowledge_service.query_research")
    @patch("routers.recommendations._save_recommendation", new_callable=AsyncMock)
    def test_disclaimer_always_present_on_ada_path(self, mock_save, mock_research, mock_gpt):
        """
        Disclaimer is appended even on the ADA fallback path (no glucose reading).
        """
        mock_research.return_value = {"status": "FALLBACK_TO_ADA"}
        mock_save.return_value = None

        # glucose_data=[] → endpoint falls back to 120 mg/dL without crashing
        with patch("db.supabase_client.supabase",
                   _mock_supabase_chain(_make_meal_row(), glucose_data=[])):
            response = client.get(f"/recommendations/{VALID_MEAL_ID}")

        self.assertEqual(response.status_code, 200)
        body = response.json()
        # Disclaimer must be the last thing appended before return
        self.assertIn(DISCLAIMER, body["recommendation"])
        self.assertEqual(body["glucose_used_mg_dl"], 120)   # fallback baseline


if __name__ == "__main__":
    unittest.main()
