"""
routers/recommendations.py
---------------------------
GET /recommendations/{meal_id}

Returns a personalised, evidence-based nutrition tip for a given meal.

Pipeline:
  1. Fetch the meal from Supabase by meal_id.
  2. Fetch the most recent glucose reading for that user.
  3. Call knowledge_service.query_research() with the food list + glucose.
  4. If research found → call GPT-4o with a strict evidence-only prompt.
     Validate that the response cites journal + year; retry once if not.
     Fall back to the ADA guideline message after two failed attempts.
  5. If FALLBACK_TO_ADA → serve the canonical ADA message.
  6. Append the mandatory disclaimer.
  7. Save the recommendation to Supabase and return.

Non-negotiable rules (do NOT relax without QA sign-off):
  - NEVER generate a recommendation without a real ChromaDB citation.
  - NEVER let GPT-4o speculate beyond the retrieved research context.
  - ALWAYS append the disclaimer before returning.
  - Reject GPT responses missing journal + year; retry once then ADA fallback.
"""

import json
import os
import re
from datetime import datetime, timezone

import httpx
from fastapi import APIRouter, HTTPException

from services import knowledge_service

router = APIRouter(prefix="/recommendations", tags=["recommendations"])

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Pre-compiled UUID v4 pattern used to validate meal_id path parameter.
_UUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    re.IGNORECASE,
)

OPENAI_API_URL = "https://api.openai.com/v1/chat/completions"

# Glucose value used when no reading exists for the user (normal fasting baseline).
FALLBACK_GLUCOSE_MG_DL = 120

# ADA canonical fallback message — served verbatim, never summarised or altered.
ADA_FALLBACK_MESSAGE = (
    "Based on American Diabetes Association guidelines, "
    "balancing your plate with lean protein, non-starchy "
    "vegetables, and complex carbs is recommended. "
    "[Source: ADA Standards of Care]"
)

# Disclaimer appended to every single recommendation output without exception.
DISCLAIMER = (
    "⚠️ Generated by AI based on recent literature. "
    "This is not medical advice. Always consult your doctor."
)

# GPT-4o system prompt — must not be altered without QA review.
GPT_SYSTEM_PROMPT = (
    "You are EviNourish, a warm and friendly nutrition assistant for people managing diabetes. "
    "Your ONLY job is to give one clear, friendly, actionable meal tip. "
    "You must only use the research context provided. "
    "If the context does not support a recommendation, say so explicitly. Do not invent or infer. "
    "Always mention the research source naturally in your response like a friendly reference, "
    "not a citation."
)


# ---------------------------------------------------------------------------
# Helper: _build_user_prompt
# ---------------------------------------------------------------------------

def _build_user_prompt(glucose: int, foods: list[str], abstract_text: str, journal: str, year: int | str) -> str:
    """Constructs the user-turn message exactly as specified."""
    return (
        f"Current glucose: {glucose} mg/dL\n"
        f"Foods on plate: {', '.join(foods)}\n"
        f"Research context: {abstract_text} ({journal}, {year})\n\n"
        "Give one warm, friendly, specific tip for eating this meal. Keep it under 3 sentences."
    )


# ---------------------------------------------------------------------------
# Helper: _call_gpt4o
# ---------------------------------------------------------------------------

async def _call_groq(system_prompt: str, user_prompt: str) -> str:
    import httpx
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        raise ValueError("GROQ_API_KEY not set")
    async with httpx.AsyncClient(timeout=60) as client:
        response = await client.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
            json={
                "model": "llama-3.3-70b-versatile",
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                "max_tokens": 500,
                "temperature": 0.7,
            }
        )
        response.raise_for_status()
        return response.json()["choices"][0]["message"]["content"].strip()


# ---------------------------------------------------------------------------
# Helper: _citation_present
# ---------------------------------------------------------------------------

def _citation_present(text: str, journal: str, year: int | str) -> bool:
    """
    Returns True if both the journal name and the year appear somewhere in the
    GPT response (case-insensitive). This is the minimum bar for accepting a
    GPT-4o response — if either is missing we retry or fall back.
    """
    text_lower = text.lower()
    return journal.lower() in text_lower and str(year) in text


# ---------------------------------------------------------------------------
# Helper: _save_recommendation
# ---------------------------------------------------------------------------

async def _save_recommendation(
    meal_id: str,
    user_id: str | None,
    recommendation_text: str,
    pubmed_id: str | None,
    glucose_at_time: int | float,
    source: str,  # "groq" or "ada_fallback"
) -> dict | None:
    """
    Persists the recommendation to Supabase.
    Non-fatal: returns None and logs a warning if Supabase is unavailable.
    """
    try:
        from db.supabase_client import supabase
    except ImportError:
        return None

    if supabase is None:
        return None

    row = {
        "meal_id": meal_id,
        "user_id": user_id,
        "recommendation_text": recommendation_text,
        "research_pubmed_id": pubmed_id,
        "glucose_at_time": glucose_at_time,
        "source": source,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }

    try:
        result = supabase.table("recommendations").insert(row).execute()
        return result.data[0] if result.data else None
    except Exception as e:
        # Non-fatal: do not fail the response if persistence fails
        print(f"[WARNING] Failed to save recommendation to Supabase: {e}")
        return None


# ---------------------------------------------------------------------------
# Endpoint: GET /recommendations/{meal_id}
# ---------------------------------------------------------------------------

@router.get("/{meal_id}")
async def get_recommendations(meal_id: str):
    """
    Returns a personalised, evidence-grounded nutrition tip for the given meal.

    Pipeline:
      1  → Validate meal_id format
      2  → Fetch meal from Supabase (404 if not found)
      3  → Extract food list from identified_foods JSONB
      4  → Fetch most recent glucose reading for the meal's user
      5  → Query ChromaDB for research context
      6  → Generate tip via GPT-4o; validate citation; retry once; ADA fallback
      7  → Append disclaimer unconditionally
      8  → Persist to recommendations table
      9  → Return unified JSON response
    """
    try:
        # ── Step 1: Validate meal_id format ──────────────────────────────
        if not meal_id or not meal_id.strip():
            raise HTTPException(status_code=400, detail="meal_id must not be empty.")

        if not _UUID_RE.match(meal_id):
            raise HTTPException(
                status_code=400,
                detail=f"meal_id '{meal_id}' is not a valid UUID v4.",
            )

        # ── Step 2: Fetch the meal from Supabase ─────────────────────────
        try:
            from db.supabase_client import supabase
        except ImportError:
            supabase = None

        meal_row: dict | None = None
        if supabase is not None:
            try:
                result = (
                    supabase.table("meals")
                    .select("*")
                    .eq("id", meal_id)
                    .limit(1)
                    .execute()
                )
                if result.data:
                    meal_row = result.data[0]
            except Exception as e:
                raise HTTPException(
                    status_code=502,
                    detail=f"Supabase error fetching meal: {str(e)}",
                )

        if meal_row is None:
            raise HTTPException(
                status_code=404,
                detail=f"Meal '{meal_id}' not found.",
            )

        user_id: str | None = meal_row.get("user_id")

        # ── Step 3: Extract food names from identified_foods JSONB ────────
        raw_foods = meal_row.get("identified_foods", [])

        # Supabase may return JSONB as a list or as a JSON string
        if isinstance(raw_foods, str):
            try:
                raw_foods = json.loads(raw_foods)
            except (json.JSONDecodeError, TypeError):
                raw_foods = []

        # Collect unique, non-empty food names
        foods: list[str] = []
        for item in (raw_foods if isinstance(raw_foods, list) else []):
            name = (item.get("food_name") or "").strip() if isinstance(item, dict) else ""
            if name and name not in foods:
                foods.append(name)

        if not foods:
            raise HTTPException(
                status_code=422,
                detail="Meal has no identifiable food items to generate a recommendation for.",
            )

        # ── Step 4: Fetch most recent glucose reading for this user ───────
        glucose: int = FALLBACK_GLUCOSE_MG_DL
        if supabase is not None and user_id:
            try:
                g_result = (
                    supabase.table("glucose_readings")
                    .select("value")
                    .eq("user_id", user_id)
                    .order("timestamp", desc=True)
                    .limit(1)
                    .execute()
                )
                if g_result.data:
                    raw_val = g_result.data[0].get("value")
                    if raw_val is not None:
                        glucose = int(float(raw_val))
                else:
                    print(
                        f"[INFO] No glucose reading found for user {user_id}; "
                        f"using fallback {FALLBACK_GLUCOSE_MG_DL} mg/dL."
                    )
            except Exception as e:
                # Non-fatal: fall back to baseline rather than crashing the tip
                print(f"[WARNING] Could not fetch glucose for user {user_id}: {e}")

        # ── Step 5: Query ChromaDB for research context ───────────────────
        try:
            research = knowledge_service.query_research(foods=foods, glucose_level=glucose)
        except (ValueError, RuntimeError) as e:
            # Typed errors from knowledge_service → serve ADA fallback
            print(f"[WARNING] knowledge_service.query_research error: {e}")
            research = {"status": "FALLBACK_TO_ADA"}
        except Exception as e:
            print(f"[WARNING] Unexpected knowledge_service error: {e}")
            research = {"status": "FALLBACK_TO_ADA"}

        # ── Step 6: Generate tip or serve ADA fallback ────────────────────
        is_ada_fallback = research.get("status") == "FALLBACK_TO_ADA"
        pubmed_id: str | None = None
        tip_text: str

        if is_ada_fallback:
            # Rule: use the exact ADA message — do NOT generate anything new
            tip_text = ADA_FALLBACK_MESSAGE
            source = "ada_fallback"
        else:
            # Unpack verified research fields
            abstract_text: str = research["abstract_text"]
            journal: str     = research.get("journal") or "Unknown Journal"
            year: int        = int(research.get("year") or 0)
            pubmed_id        = research.get("pubmed_id")

            user_prompt = _build_user_prompt(glucose, foods, abstract_text, journal, year)

            # First attempt
            gpt_response = await _call_groq(GPT_SYSTEM_PROMPT, user_prompt)

            # Citation validation — reject if journal + year not present in output
            if not _citation_present(gpt_response, journal, year):
                # Retry once with the same prompt
                gpt_response = await _call_groq(GPT_SYSTEM_PROMPT, user_prompt)

                # Second attempt also failed → serve ADA fallback
                if not _citation_present(gpt_response, journal, year):
                    is_ada_fallback = True
                    tip_text = ADA_FALLBACK_MESSAGE
                    source = "ada_fallback"
                else:
                    tip_text = gpt_response
                    source = "groq"
            else:
                tip_text = gpt_response
                source = "groq"

        # ── Step 7: Append disclaimer unconditionally ─────────────────────
        # The disclaimer is appended after every path — ADA fallback and GPT both.
        recommendation = f"{tip_text}\n\n{DISCLAIMER}"

        # ── Step 8: Persist to Supabase recommendations table ────────────
        await _save_recommendation(
            meal_id=meal_id,
            user_id=user_id,
            recommendation_text=recommendation,
            pubmed_id=pubmed_id,
            glucose_at_time=glucose,
            source=source,
        )

        # ── Step 9: Return unified response ──────────────────────────────
        return {
            "status": "success",
            "meal_id": meal_id,
            "recommendation": recommendation,
            "source": source,
            "glucose_used_mg_dl": glucose,
            "research": None if is_ada_fallback else {
                "pubmed_id": pubmed_id,
                "journal": research.get("journal"),
                "year": research.get("year"),
                "similarity": research.get("similarity"),
            },
        }

    except HTTPException:
        raise  # Re-raise validation / routing errors as-is
    except Exception as e:
        # TODO: Replace with structured logger once logging infrastructure exists
        raise HTTPException(status_code=500, detail=str(e))
